#define BUILDCACHE_VERSION_MAJOR 0
#define BUILDCACHE_VERSION_MINOR 18
#define BUILDCACHE_VERSION_PATCH 0
#define BUILDCACHE_VERSION_STRING "0.18.0"

#define BUILDCACHE_COPYRIGHT_STRING "Copyright (c) 2018-2020 Marcus Geelnard"

