#define BUILDCACHE_VERSION_MAJOR 0
#define BUILDCACHE_VERSION_MINOR 10
#define BUILDCACHE_VERSION_PATCH 1
#define BUILDCACHE_VERSION_STRING "0.10.1"

#define BUILDCACHE_COPYRIGHT_STRING "Copyright (c) 2019 Marcus Geelnard"

