#define BUILDCACHE_VERSION_MAJOR 0
#define BUILDCACHE_VERSION_MINOR 7
#define BUILDCACHE_VERSION_PATCH 2
#define BUILDCACHE_VERSION_STRING "0.7.2"

#define BUILDCACHE_COPYRIGHT_STRING "Copyright (c) 2019 Marcus Geelnard"

