name: Build and Test

on:
  push:
    branches:
      - master
    tags:
      - v*
  pull_request:
  workflow_dispatch:

env:
  BUILD_TYPE: Release

jobs:
  build:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
        - {
            name: "Windows Latest MSVC",
            artifact: "buildcache-win-msvc.zip",
            artifact_format: "zip",
            os: windows-latest,
            cc: "cl",
            cxx: "cl",
            environment_script: "C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Auxiliary/Build/vcvars64.bat"
          }
        - {
            name: "Windows Latest MinGW",
            artifact: "buildcache-win-mingw.zip",
            artifact_format: "zip",
            os: windows-latest,
            cc: "gcc",
            cxx: "g++"
          }
        - {
            name: "Ubuntu 20.04 GCC",
            artifact: "buildcache-linux.tar.gz",
            artifact_format: "gnutar",
            artifact_tar_flags: "z",
            os: ubuntu-20.04,
            cc: "gcc",
            cxx: "g++"
          }
        - {
            name: "macOS Latest Clang",
            artifact: "buildcache-macos.zip",
            artifact_format: "zip",
            os: macos-latest,
            cc: "clang",
            cxx: "clang++"
          }

    steps:
    - uses: actions/checkout@v1

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8.x

    - name: Setup CMake and Ninja
      uses: lukka/get-cmake@latest

    - name: Setup Clang tools
      if: ${{ runner.os == 'Linux' }}
      run: |
        sudo apt update
        sudo apt install -y clang-tidy clang-format

    - name: Configure
      shell: cmake -P {0}
      run: |
        set(ENV{CC} ${{ matrix.config.cc }})
        set(ENV{CXX} ${{ matrix.config.cxx }})

        # Capture environment variables (preserve the effect of MSVC vcvars.bat).
        if ("${{ runner.os }}" STREQUAL "Windows" AND NOT "x${{ matrix.config.environment_script }}" STREQUAL "x")
          execute_process(
            COMMAND "${{ matrix.config.environment_script }}" && set
            OUTPUT_FILE environment_script_output.txt
          )
          file(STRINGS environment_script_output.txt output_lines)
          foreach(line IN LISTS output_lines)
            if (line MATCHES "^([a-zA-Z0-9_-]+)=(.*)$")
              set(ENV{${CMAKE_MATCH_1}} "${CMAKE_MATCH_2}")
            endif()
          endforeach()
        endif()

        # Build universal binaries on macOS.
        if ("${{ runner.os }}" STREQUAL "macOS")
          set(ENV{CMAKE_OSX_ARCHITECTURES} "x86_64;arm64")
        endif()

        execute_process(
          COMMAND cmake
            -S src
            -B build
            -D CMAKE_BUILD_TYPE=$ENV{BUILD_TYPE}
            -G Ninja
          RESULT_VARIABLE result
        )
        if (NOT result EQUAL 0)
          message(FATAL_ERROR "Bad exit status")
        endif()


    - name: Build
      shell: cmake -P {0}
      run: |
        set(ENV{NINJA_STATUS} "[%f/%t %o/sec] ")

        # Resture environment variables (apply the effect of MSVC vcvars.bat).
        if ("${{ runner.os }}" STREQUAL "Windows" AND NOT "x${{ matrix.config.environment_script }}" STREQUAL "x")
          file(STRINGS environment_script_output.txt output_lines)
          foreach(line IN LISTS output_lines)
            if (line MATCHES "^([a-zA-Z0-9_-]+)=(.*)$")
              set(ENV{${CMAKE_MATCH_1}} "${CMAKE_MATCH_2}")
            endif()
          endforeach()
        endif()

        execute_process(
          COMMAND cmake --build build
          RESULT_VARIABLE result
        )
        if (NOT result EQUAL 0)
          message(FATAL_ERROR "Bad exit status")
        endif()


    - name: Run unit tests
      shell: cmake -P {0}
      run: |
        include(ProcessorCount)
        ProcessorCount(N)

        set(ENV{CTEST_OUTPUT_ON_FAILURE} "ON")

        execute_process(
          COMMAND ctest -j ${N}
          WORKING_DIRECTORY build
          RESULT_VARIABLE result
        )
        if (NOT result EQUAL 0)
          message(FATAL_ERROR "Running tests failed!")
        endif()


    - name: Run system tests
      if: ${{ runner.os != 'Windows' }}
      working-directory: build
      run: |
        ../test_scripts/run_file_lock_stresstest.sh
        ../test_scripts/build_with_buildcache.sh


    - name: Run static checks
      if: ${{ runner.os == 'Linux' }}
      run: test_scripts/run_linters.py -p build


    - name: Install Strip
      run: cmake --install build --prefix buildcache --strip


    - name: Pack
      run: cmake -E tar cv${{ matrix.config.artifact_tar_flags }}f ${{ matrix.config.artifact }} --format=${{ matrix.config.artifact_format }} buildcache


    - name: Upload
      uses: actions/upload-artifact@v1
      with:
        path: ./${{ matrix.config.artifact }}
        name: ${{ matrix.config.artifact }}

  release:
    if: contains(github.ref, 'tags/v')
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1.0.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false

    - name: Store Release url
      run: |
        echo "${{ steps.create_release.outputs.upload_url }}" > ./upload_url

    - uses: actions/upload-artifact@v1
      with:
        path: ./upload_url
        name: upload_url

  publish:
    if: contains(github.ref, 'tags/v')
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
        - {
            name: "Windows Latest MSVC",
            artifact: "buildcache-win-msvc.zip",
            artifact_content_type: "application/zip",
            os: ubuntu-latest
          }
        - {
            name: "Windows Latest MinGW",
            artifact: "buildcache-win-mingw.zip",
            artifact_content_type: "application/zip",
            os: ubuntu-latest
          }
        - {
            name: "Ubuntu Latest GCC",
            artifact: "buildcache-linux.tar.gz",
            artifact_content_type: "application/gzip",
            os: ubuntu-latest
          }
        - {
            name: "macOS Latest Clang",
            artifact: "buildcache-macos.zip",
            artifact_content_type: "application/zip",
            os: ubuntu-latest
          }
    needs: release

    steps:
    - name: Download artifact
      uses: actions/download-artifact@v1
      with:
        name: ${{ matrix.config.artifact }}
        path: ./

    - name: Download URL
      uses: actions/download-artifact@v1
      with:
        name: upload_url
        path: ./
    - id: set_upload_url
      run: |
        upload_url=`cat ./upload_url`
        echo ::set-output name=upload_url::$upload_url

    - name: Upload to Release
      id: upload_to_release
      uses: actions/upload-release-asset@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.set_upload_url.outputs.upload_url }}
        asset_path: ./${{ matrix.config.artifact }}
        asset_name: ${{ matrix.config.artifact }}
        asset_content_type: ${{ matrix.config.artifact_content_type }}
